name: RN Github Action

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  PROJECT_NAME: RNGithubAction

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        rn_version: ['0.68.x', '0.67.x', '0.66.x', '0.65.x', '0.64.x', '0.63.x', '0.62.x', '0.61.x', '0.60.x']
        node_version: ['18.x', '16.x', '14.x', '12.x', '10.x']

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.1
        with:
          # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
          node-version: 18.x
          
      - name: Setup Java JDK
        uses: actions/setup-java@v3.2.0
        with:
          # The Java version to set up. Takes a whole or semver Java version. See examples of supported syntax in README file
          java-version: '11'
          # Java distribution. See the list of supported distributions in README file
          distribution: 'zulu'
      

      # Runs a single command using the runners shell
      - name: Create new react native project
        run: npx react-native init RNGithubAction --version ${{ matrix.rn_version }}
        
      - name: Make Gradlew Executable
        run: cd $PROJECT_NAME && cd android && chmod +x ./gradlew
        
      - name: Generate App APK
        run: |
          cd $PROJECT_NAME && cd android && ./gradlew assembleRelease --no-daemon
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          # Artifact name
          name: 'build'
          path: 'RNGithubAction/android/app/build/outputs/apk/release/app-release.apk'
